version: '3.5'
services:
  ProductService:
   image: ${DOCKER_REGISTRY-}productmicroservice:v1
   build:
    context: ./ProductMicroservice
    dockerfile: Dockerfile
   environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.1.11,1433;Initial Catalog=ProductServiceDB;User Id=sa;Password=Liououm@9172;"
   ports:
    - "4201:80"
  UserService:
   image: ${DOCKER_REGISTRY-}usermicroservice:v1
   build:
    context: ./UserMicroservice
    dockerfile: Dockerfile
   environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.1.11,1433;Initial Catalog=UserServiceDB;User Id=sa;Password=Liououm@9172;"
   ports:
    - "4202:80"